---
- name: install center arrow theme
  unarchive:
    src: "{{ centerrow_dl_url }}/v{{ centerrow_version }}/centerrow-v{{ centerrow_version }}.zip"
    dest: "{{ item.documentroot }}/omeka-s/themes/"
    remote_src: true
  with_items:
    - "{{ apache_vhosts }}"
