---
- name: perconadb | install gnupg
  apt:
    name: ["gnupg2"]
    state: present
    update_cache: true

- name: perconadb | set percona repository
  apt:
    deb: "{{ repository_url }}{{ ansible_distribution_release }}_all.deb"

- name: perconadb | install percona 
  apt:
    name: "{{ percona_server }}"
    state: present
    update_cache: true

- include_tasks: configure.yml

- name: perconadb | enable and start mysql
  service:
    name: "{{ mysql_service }}"
    state: started
    enabled: true

- name: perconadb | create databases
  mysql_db:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    target: "{{ item.target | default(omit) }}"
    encoding: "{{ item.encoding | default(omit) }}"
    collation: "{{ item.collation | default(omit) }}"
    #login_unix_socket: "{{ mysql_socket }}"
  loop: "{{ mysql_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - mysql_databases is defined

- name: perconadb | create users
  mysql_user:
    name: "{{ item.name }}"
    state: present
    password: "{{ item.password | default(omit) }}"
    priv: "{{ item.priv | default(omit) }}"
    host: "{{ item.host | default(omit) }}"
    update_password: "{{ item.update_password | default('on_create') }}"
    #login_unix_socket: "{{ mysql_socket }}"
  loop: "{{ mysql_users }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - mysql_users is defined
  no_log: false

- name: flush handlers
  meta: flush_handlers

