---
# tasks file for php
- name: php | install php
  apt:
    name: "{{ php_packages }}"
    state: present
    update_cache: true

- name: php | configure php
  ini_file:
    dest: "{{ php_ini_location }}"
    section: "{{ item.value.section }}"
    option: "{{ item.key }}"
    value: "{{ item.value.value }}"
    mode: "0644"
  with_dict: "{{ php_settings }}"
  notify:
    - restart apache
  loop_control:
    label: "{{ item.key }}"

