---
- hosts: percona
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/gcp/bastion_example.yml
    - ../group_vars/perconadb/db_example.yml
    - ../group_vars/omeka_site_example/omeka_site_example.yml
  roles:
    - role: ../roles/perconadb

- hosts: omekaapp
  remote_user: pulsys
  become: true
  vars_files:
    - ../group_vars/gcp/bastion_example.yml
    - ../group_vars/perconadb/db_example.yml
    - ../group_vars/omeka_site_example/omeka_site_example.yml
  roles:
    - role: ../roles/omeka_site
