---
# tasks file for omeka
#
- name: omeka | install php dependencies
  apt:
    name: "{{ omeka_dependencies }}"
    state: present
    update_cache: true
  notify:
    - restart apache

- name: omeka | register downloaded
  stat:
    path: "{{ omeka_web_root }}"
  register: omeka_downloaded

- name: omeka | unarchive omeka
  unarchive:
    src: "{{ omeka_url }}/v{{ omeka_version }}/omeka-s-{{ omeka_version }}.zip"
    dest: "{{ web_root }}"
    remote_src: true